### ISSUE TITLE
googleログインでのエラー

### ISSUE THREAD

**Issue by miki-hayashi-71** [miki-hayashi-71/Sence_Of_Distance#169]
### エラー内容
- sorceryのexternalモジュールを用いたgoogleログインの実装において、`OAuth2::Error in OauthsController#callback`が発生
[![Image from Gyazo](https://i.gyazo.com/8d7510999b51e1c5b727a2bbc1f68d9f.gif)](https://gyazo.com/8d7510999b51e1c5b727a2bbc1f68d9f)
[![Image from Gyazo](https://i.gyazo.com/a7f6692109f546024521e2aae5695474.png)](https://gyazo.com/a7f6692109f546024521e2aae5695474)

### 解決したいこと 
- google側からアプリ側に正しく遷移し、ログインができるようにしたい。
- エラー内容から、「リクエスト時のパラメータにおいて、`response_type`に`code`を設定する」必要があると予測しているが、その設定の仕方がわからない。
- sorceryを用いた外部ログインの記事やGitHubのディレクトリもいくつか見てみたが、あえてこの値を設定するような段取りがないため、何に起因してこのエラーが発生しているのか分からない。
  - `verify_g_csrf_token`メソッドについても、現状ないとエラーとなるが、sorceryのドキュメントや記事にはこのメソッドについて特段記述がないのも気になる。

### 参考資料
[Rails】Sorceryを使用したGoogle認証機能の追加](https://qiita.com/okada84108983/items/0c84c01b88072c004873)
[sorceryのドキュメント](https://github.com/Sorcery/sorcery/wiki/External)

**Comment by kenchasonakai** [comment]
現状のコードがどうなっているのか確認したいので関係ありそうなところのコードの共有やプルリクエストの作成をお願いします

**Comment by miki-hayashi-71** [comment]
[プルリク](https://github.com/miki-hayashi-71/Sence_Of_Distance/pull/170)を作成しました。
よろしくお願いします。

**Comment by kenchasonakai** [comment]
プルリクにコメントしました
https://github.com/miki-hayashi-71/Sence_Of_Distance/pull/170

**Comment by kenchasonakai** [comment]
プルリクにコメントしました
https://github.com/miki-hayashi-71/Sence_Of_Distance/pull/170#issuecomment-2441185884
