### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by miki-hayashi-71** [miki-hayashi-71/Sence_Of_Distance#25]
### 実装予定の機能
- [ ] 出発地点と到着地点の入力機能
- [ ] 現在位置、特定の別地点の登録機能
- [ ] 基準ルートの距離計算機能
- [ ] 比較ルートの到着地点提案機能
- [ ] 比較結果の地図表示機能
- [ ] 履歴の保存・表示機能
- [ ] ユーザー登録・ログイン機能

### 必要なページ
- [ ] トップページ
- [ ] 各地点入力画面
- [ ] 比較結果画面
- [ ] 比較履歴画面
- [ ] 新規ユーザー登録画面
- [ ] ログイン画面
- [ ] マイページ画面
- [ ] ユーザー名変更画面
- [ ] メールアドレス変更画面
- [ ] 利用規約画面
- [ ] プライバシーポリシー画面
- [ ] お問い合わせフォーム画面

**Comment by kashiwagi-rena** [comment]
お疲れ様です。
ストーリーポイント5のものがかなり多く存在していました。
5はかなり大きいと予想されますので、分けれるものを分けていただきたいです。
(API関連のものがわからずそうなっていることは、ちゃんと理解しています。少し調べてわかるものだけでも対応していただきたいです。)

**Comment by tmtkzk0823** [comment]
柏木講師からのレビューはご対応いただけた形でしょうか？
ご対応いただけた場合、その旨をコメント欄にてご報告をおねがいします。
以下、追加のコメントです。

---

-デプロイ、rails newなどのカードも作成もお願いします。

**Comment by miki-hayashi-71** [comment]
ご確認いただきありがとうございます。
コメントを送信しないままレビュー依頼をおくっておりました。
申し訳ありません。

柏木講師からのレビューには対応済みです。
対応内容は、API関連のカードで
ストーリーポイントが5になっていたものについて、カードを分割しました。

また、今回、デプロイとrails newについてのカードを追加で作成しました。

ご確認のほどよろしくお願いします。

**Comment by Tsuchiya2** [comment]
カードにストーリーポイントが付けられていないものがありましたので対応をお願いいたします。

概ね良いかと思います。LGTMです。

---

以下、MVP後でも良いと思ったカードになります。
- i18nによる日本語化対応
- 利用規約
- プライバシーポリシー
- お問い合わせ
- 比較履歴
- 履歴
- マイページ
- ユーザー名、メールアドレスの変更
- （MVP後）のカード

**Comment by miki-hayashi-71** [comment]
ありがとうございます！
ご指摘いただいた内容を反映し、スケジュール面談を申し込みます。
