### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by miki-hayashi-71** [miki-hayashi-71/Sence_Of_Distance#78]
## 各種情報
サービス名：距離感どのくらい？
サービスURL：[https://sence-of- distance.onrender.com](https://sence-of-distance.onrender.com/)

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] Geocoding APIを使用した出発地点と到着地点の入力機能
- [ ] Geocoding APIを使用した自宅、現在位置、特定の別地点の登録機能
- [ ] Distance Matrix APIと Distance Matrix APIを使用した旅行先の距離計算と自宅周辺の地点提案機能
- [ ] Maps JavaScript APIを使用した地図の表示と距離比較結果の視覚化機能

## READMEレビュー時から変更した機能
上記全てを実装することをメインの機能とすることが難しいと判断したため、機能を減らして、アプリの目的を変更しました。
【距離比較アプリ】→【距離を当てるクイズアプリ】
- [x] Distance Matrix APIを使用し、ランダムで取得した2点間の距離を計算し、クイズの選択肢として表示する機能

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/6f199a50d153ae074eccbba69b6368bb.png)](https://gyazo.com/6f199a50d153ae074eccbba69b6368bb)

[![Image from Gyazo](https://i.gyazo.com/b0ba941c54625c18a132f36a942c9b1e.gif)](https://gyazo.com/b0ba941c54625c18a132f36a942c9b1e)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by miki-hayashi-71** [comment]
ありがとうございます！！
これからもよろしくお願いします！
